### ISSUE TITLE
workflows section in web site does not work

### ISSUE THREAD

**Issue by salma1601** [nipy/dipy_web#35]
Hi
In the website http://elef.soic.indiana.edu/tutorials/
I get the message
>Something went wrong with this tutorial. Please report the issue here.

for the workflows section.

Thanks!

**Comment by ghoshbishakh** [comment]
@salma1601 thank you for reporting!

This should be fixed with a new build of the docs.

**Comment by jchoude** [comment]
@salma1601 When looking rigfht now, everything seems to be good. Did you see that just for a specific section,or all of them? If this is fixed, I'll close the issue.

**Comment by salma1601** [comment]
![dipy_web](https://cloud.githubusercontent.com/assets/7080143/24449218/09ad5cf0-1477-11e7-8c35-37c7ed36c32d.png)

I see that only for the Workflows section

**Comment by jchoude** [comment]
@ghoshbishakh Are we supposed to be good to go with the PRs that were merged in Dipy? The website still seems to have that issue, maybe it's just a matter of pushing to the server...

**Comment by ghoshbishakh** [comment]
@jchoude I was unable to build the docs due to some issues [#1218](https://github.com/nipy/dipy/issues/1218)[ #1215](https://github.com/nipy/dipy/issues/1215) which are now resolved.

I have to build it and upload it but now but it takes a lot of time (days) in my PC. I will try to update it within this weekend.

**Comment by ghoshbishakh** [comment]
@jchoude fixed!
